config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :partners, only: [:new, :create, :edit, :update, :destroy] do
    get '/keywords', to: 'keywords#index'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get 'events/loading', to: 'events#loading'
  resources :events, except: :index
  get '/dashboard', to: 'events#uncompleted_events', as: :dashboard
  get '/events/:id/success', to: 'events#edit_success', as: :success
  patch '/events/:id/success', to: 'events#update_success'
  get '/completed_events', to: 'events#completed_events', as: :history
  get '/us/', to: 'users#us', as: :us
  get '/settings/', to: 'users#setting', as: :setting
  get 'users/:id/edit', to: 'users#edit', as: :edit
  patch 'users/:id', to: "users#update", as: :update
  resources :inspos, only: %i[index edit update] do
    member do
      post 'toggle_favorite', to: "inspos#toggle_favorite"
      post 'toggle_blocked', to: "inspos#toggle_blocked"
    end
  end
  get '/preferences/create', to: 'preferences#create'
  get '/preferences/destroy', to: 'preferences#destroy'
  as :user do
    get '/us/', to: 'devise/registrations#edit', as: :user_root
  end
end

app/views/shared/_avatar.html.erb
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fzultimate.com%2Fwp-content%2Fuploads%2F2019%2F12%2Fdefault-profile.png&f=1&nofb=1" alt="avatar" class="avatar">

app/views/shared/_edit-setting-card-frequency.html.erb
<div class="event-card d-none" data-settings-target="editFrequency">
  <div class="event-card-content">
    <p class="event-icon color-dark">
      <i class="fa-solid fa-calendar-days"></i>
    </p>
    <div class="event-card-info">
      <h6>
        Event Frequency
      </h6>
    </div>
    <p><i class="fa-solid fa-chevron-up" data-action="click->settings#hideEdit"></i></p>
  </div>
    <div class="event-description">
      <%= simple_form_for(current_user, url: update_path(current_user)) do |f| %>
        <%= f.input :event_frequency, label:"# of events per month" %>
        <%= f.submit "Confirm", class: "btn btn-flat" %>
      <% end %>
    </div>
</div>

app/views/shared/_edit-setting-card-payment.html.erb
<div class="event-card d-none" data-settings-target="editPayment">
  <div class="event-card-content">
    <p class="event-icon color-dark">
      <i class="fa-solid fa-money-bill-wave"></i>
    </p>
    <div class="event-card-info">
      <h6>
        Payment
      </h6>
    </div>
    <p><i class="fa-solid fa-chevron-up" data-action="click->settings#hidePayment"></i></p>
  </div>
    <div class="event-description">
      <%= simple_form_for(current_user, url: update_path(current_user)) do |f| %>
        <%= f.input :budget, label:"Budget per gift", input_html: { value: number_with_precision(current_user.budget, precision: 2) } %>
        <%= f.submit "Confirm", class: "btn btn-flat" %>
      <% end %>
    </div>
</div>

app/views/shared/_event-card-completed.html.erb
<div class="event-card" data-edit-event-target="completed" id="event-<%= event.id %>">
  <div class="event-card-content">
    <p class="event-icon color-blue" data-action="click->edit-event#eventSuccess">
      <% if event.success %>
        <i class="icon-thumb fa-solid fa-thumbs-up" id="<%= event.id %>" data-edit-event-target="success"></i>
      <% else %>
        <i class="icon-thumb fa-regular fa-thumbs-up" id="<%= event.id %>" data-edit-event-target="success"></i>
      <% end %>
    </p>
    <div class="event-card-info">
      <h6>
        <%= event.inspo.name %>
        <% if event.inspo.genre == "date" %>
          <i class="fa-solid fa-people-pulling"></i>
        <% elsif event.inspo.genre == "gift" %>
          <i class="fa-solid fa-gift"></i>
        <% elsif event.inspo.genre == "text" %>
          <i class="fa-solid fa-comment-dots"></i>
        <% end %>
      </h6>
      <p>Completed</p>
    </div>
    <p><i class="fa-solid fa-chevron-down" data-action="click->edit-event#revealShowCompleted" id="event-<%= event.id %>"></i></p>
  </div>
</div>

app/views/shared/_event-card-confirmed.html.erb
<div class="event-card" data-edit-event-target="confirmed" id="event-<%= event.id %>">
  <div class="event-card-content">
    <p class="event-icon color-orange"><i class="fa-solid fa-calendar-check"></i></p>
    <div class="event-card-info">
      <h6>
        <%= event.inspo.name %>
        <% if event.inspo.genre == "date" %>
          <i class="fa-solid fa-people-pulling"></i>
        <% elsif event.inspo.genre == "gift" %>
          <i class="fa-solid fa-gift"></i>
        <% elsif event.inspo.genre == "text" %>
          <i class="fa-solid fa-comment-dots"></i>
        <% end %>
      </h6>
      <p>Scheduled</p>
    </div>
    <p><i class="fa-solid fa-chevron-down" data-action="click->edit-event#revealShowConfirmed" id="event-<%= event.id %>"></i></p>
  </div>
</div>

app/views/shared/_event-card-pending.html.erb
<div class="event-card pending-event" data-edit-event-target="pending" id="event-<%= event.id %>">
  <div class="event-card-content">
    <p class="event-icon color-red"><i class="fa-solid fa-circle-exclamation"></i></p>
    <div class="event-card-info">
      <h6>
        <%= event.inspo.name %>
        <% if event.inspo.genre == "date" %>
          <i class="fa-solid fa-people-pulling"></i>
        <% elsif event.inspo.genre == "gift" %>
          <i class="fa-solid fa-gift"></i>
        <% elsif event.inspo.genre == "text" %>
          <i class="fa-solid fa-comment-dots"></i>
        <% end %>
      </h6>
      <p>Pending Confirmation</p>
    </div>
    <p><i class="fa-solid fa-chevron-down" data-action="click->edit-event#revealEdit" id="event-<%= event.id %>"></i></p>
  </div>
</div>

app/views/shared/_event-card.html.erb
<%= link_to (event_path(event)) do %>
  <div class="event-card">
    <div class="event-card-content">
      <% if event.pending? %>
        <p class="event-icon color-red">
          <i class="fa-solid fa-circle-exclamation"></i>
        </p>
      <% elsif event.confirmed? %>
        <p class="event-icon color-orange">
          <i class="fa-solid fa-calendar-check"></i>
        </p>
      <% elsif event.completed? %>
        <p class="event-icon color-blue">
          <i class="fa-regular fa-thumbs-up"></i>
        </p>
      <% end %>
      <div class="event-card-info">
        <h6>
          <%= event.inspo.name %>
          <% if event.inspo.genre == "date" %>
            <i class="fa-solid fa-people-pulling"></i>
          <% elsif event.inspo.genre == "gift" %>
            <i class="fa-solid fa-gift"></i>
          <% elsif event.inspo.genre == "text" %>
            <i class="fa-solid fa-comment-dots"></i>
          <% end %>
        </h6>
        <p>
          <% if event.pending? %>
            Awaiting Confirmation
          <% elsif event.confirmed? %>
            Scheduled
          <% elsif event.completed? %>
            Completed
          <% end %>
        </p>
      </div>
      <p><i class="fa-solid fa-angle-right"></i></p>
    </div>
  </div>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_inspo-card.html.erb
<div class="inspo-card-container d-none" data-swipe-inspos-target="inspo" data-index=<%= index %>>
  <% url = inspo.photo.attached? ? (cl_image_path inspo.photo.key, height: 450, width: 350, crop: :fill) : "/assets/inspo_default.jpg" %>
  <div class="inspo-card" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(<%= url %>)">
    <div class="inspo-card-content">
      <div class="inspo-card-info">
        <h4><%= inspo.genre.capitalize %>: </h4>
        <h2><%= inspo.name %></h2>
      </div>
    </div>
    <div class="inspo-card-buttons" data-action="click->swipe-inspos#revealNextCard">
      <%= link_to ('<i class="dislike"><i class="fa-solid fa-xmark"></i></i>').html_safe, toggle_blocked_inspo_path(inspo), data: {turbo_method: :post} %>
      <%= link_to ('<i class="like"><i class="fa-solid fa-heart"></i></i>').html_safe, toggle_favorite_inspo_path(inspo), data: {turbo_method: :post} %>
    </div>
  </div>
  <h4 class="text-center mb-2"><%= index + 1 %> / <%= total %></h4>
</div>

app/views/shared/_loading.html.erb
<div class="inspo-card-container d-none" data-swipe-inspos-target="inspo" style="">
  <% url = "/assets/inspo_default_blur.jpg" %>
  <div class="inspo-card" style="background-image: url(<%= url %>);">
    <%= link_to 'Generate Events!', events_loading_path, class:"btn btn-flat"%>
  </div>
  <h4 class="text-center mb-2" style="color: #FFFEFE">have a nice day</h4>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-ficelle">
  <ul>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to(dashboard_path) do %>
          <p class="nav-icon"><i class="fa-solid fa-house <%= 'my-nav' if request.fullpath == dashboard_path %>"></i></p>
          <p class="nav-info">dashboard</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(history_path) do %>
          <p class="nav-icon"><i class="fa-solid fa-list-ul <%= 'my-nav' if request.fullpath == history_path %>"></i></p>
          <p class="nav-info">past events</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(us_path) do %>
          <% my_nav = false %>
          <% my_nav = true if request.fullpath == us_path || request.fullpath == edit_user_registration_path %>
          <% if current_user.partner %>
            <% my_nav = true if request.fullpath == edit_partner_path(current_user.partner) || request.fullpath == partner_keywords_path(current_user.partner) %>
          <% end %>
          <p class="nav-icon"><i class="fa-solid fa-user-group <%= my_nav ? 'my-nav' : '' %>"></i></p>
          <p class="nav-info">relationship</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(inspos_path) do %>
          <p class="nav-icon"><i class="fa-solid fa-hand-holding-heart <%= 'my-nav' if request.fullpath == inspos_path %>"></i></p>
          <p class="nav-info">inspiration</p>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(setting_path) do %>
          <p class="nav-icon"><i class="fa-solid fa-gear <%= 'my-nav' if request.fullpath == setting_path %>"></i></p>
          <p class="nav-info">settings</p>
        <% end %>
      </li>

      <%# <li class="nav-item"> %>
        <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      <%# </li> %>
      <%# put above logout into settings %>

    <%# else %>
      <%# <li class="nav-item"> %>
        <%#= link_to "Login", new_user_session_path %>
      <%# </li> %>
    <% end %>
  </ul>
</div>

app/views/shared/_setting-card-frequency.html.erb
<div class="event-card" data-settings-target="frequency">
  <div class="event-card-content">
    <p class="event-icon color-dark">
     <i class="fa-solid fa-calendar-days"></i>
    </p>
     <div class="event-card-info">
        <h6>
          Event Frequency
        </h6>
      </div>
    <p><i class="fa-solid fa-chevron-down" data-action="click->settings#revealEdit"></i></p>
  </div>
</div>

app/views/shared/_setting-card-payment.html.erb
<div class="event-card" data-settings-target="payment">
  <div class="event-card-content">
    <p class="event-icon color-dark">
      <i class="fa-solid fa-money-bill-wave"></i>
    </p>
    <div class="event-card-info">
      <h6>
        Payment
      </h6>
    </div>
    <p><i class="fa-solid fa-chevron-down" data-action="click->settings#revealPayment"></i></p>
  </div>
</div>

app/views/shared/_show-event-card.html.erb
<div class="event-card d-none" data-edit-event-target="show" id="event-<%= event.id %>">
  <div class="event-card-content">
    <% if event.pending? %>
      <p class="event-icon color-red">
        <i class="fa-solid fa-circle-exclamation"></i>
      </p>
    <% elsif event.confirmed? %>
      <p class="event-icon color-orange">
        <i class="fa-solid fa-calendar-check"></i>
      </p>
    <% elsif event.completed? %>
      <p class="event-icon color-blue" data-action="click->edit-event#eventSuccess">
        <% if event.success %>
          <i class="icon-thumb fa-solid fa-thumbs-up" id="<%= event.id %>" data-edit-event-target="success"></i>
        <% else %>
          <i class="icon-thumb fa-regular fa-thumbs-up" id="<%= event.id %>" data-edit-event-target="success"></i>
        <% end %>
      </p>
    <% end %>
    <div class="event-card-info">
      <h6>
        <%= event.inspo.name %>
        <% if event.inspo.genre == "date" %>
          <i class="fa-solid fa-people-pulling"></i>
        <% elsif event.inspo.genre == "gift" %>
          <i class="fa-solid fa-gift"></i>
        <% elsif event.inspo.genre == "text" %>
          <i class="fa-solid fa-comment-dots"></i>
        <% end %>
      </h6>
      <p>
        <% if event.pending? %>
          Pending confirmation
        <% elsif event.confirmed? %>
          Scheduled
        <% elsif event.completed? %>
          Completed
        <% end %>
      </p>
    </div>
    <p><i class="fa-solid fa-chevron-up"
    <% if event.confirmed? %>
      data-action="click->edit-event#hideShowConfirmed"
    <% elsif event.completed? %>
      data-action="click->edit-event#hideShowCompleted"
    <% end %>
     id="event-<%= event.id %>"></i></p>
  </div>
  <div class="event-description">
    <p><strong>Event Type: </strong><br><%= event.inspo.genre.capitalize %></p>
    <p><strong>Event Date: </strong><br><%= event.date
    .in_time_zone('Eastern Time (US & Canada)').strftime("%A, %b %e at %l:%M %p") %></p>
    <% if event.inspo.genre == "text" %>
      <% if event.content%>
        <p><strong>Content: </strong><br><%= event.content %></p>
      <% end %>
    <% elsif event.inspo.genre == "date" %>
      <% if event.inspo.location %>
        <p><strong>Location: </strong><br><%= event.inspo.location %></p>
      <% end %>
    <% end %>
    <% if event.inspo.cost %>
      <p><strong>Cost: </strong><br><%= number_to_currency(event.inspo.cost) %></p>
    <% end %>
    <% if event.confirmed? %>
      <%= link_to "Delete Event",
        event_path(event),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?"},
        class: "btn btn-flat"
      %>
    <% end %>
  </div>
</div>