config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :partners, only: [:new, :create, :edit, :update, :destroy] do
    get '/keywords', to: 'keywords#index'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get 'events/loading', to: 'events#loading'
  resources :events, except: :index
  get '/dashboard', to: 'events#uncompleted_events', as: :dashboard
  get '/events/:id/success', to: 'events#edit_success', as: :success
  patch '/events/:id/success', to: 'events#update_success'
  get '/completed_events', to: 'events#completed_events', as: :history
  get '/us/', to: 'users#us', as: :us
  get '/settings/', to: 'users#setting', as: :setting
  get 'users/:id/edit', to: 'users#edit', as: :edit
  patch 'users/:id', to: "users#update", as: :update
  resources :inspos, only: %i[index edit update] do
    member do
      post 'toggle_favorite', to: "inspos#toggle_favorite"
      post 'toggle_blocked', to: "inspos#toggle_blocked"
    end
  end
  get '/preferences/create', to: 'preferences#create'
  get '/preferences/destroy', to: 'preferences#destroy'
  as :user do
    get '/us/', to: 'devise/registrations#edit', as: :user_root
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :partner
  belongs_to :inspo

  enum status: { pending: 0, confirmed: 1, completed: 2 }

  validates :date, presence: true

  def self.load(user)
    Event.destroy_all
    year, month, day = Date.today.year, Date.today.month, Date.today.day
    Favorite.for_favoritor(user).sample(user.event_frequency).each do |favorite|
      inspo = Inspo.find(favorite.favoritable_id)
      unless user.blocked_by?(inspo)
        if Event.where(inspo_id: inspo.id).empty?
          if inspo.genre == 'text'
            date = Time.new(year, month, day, rand(8..20), [15, 30, 45, 0].sample) + (86400 * rand(1..5))
          elsif inspo.genre == 'gift'
            date = Time.new(year, month, day, rand(8..20)) + (86400 * rand(1..7))
          else
            date = Time.new(year, month, day, rand(17..19)) + (86400 * rand(1..14))
          end
          media = inspo.genre == 'text' ? inspo.media : nil
          content = inspo.genre == 'text' ? inspo.content : nil
          event = Event.new(date: date, content: content)
          event.partner = user.partner
          event.inspo = inspo
          event.save!
        end
      end
    end
    %w[text gift date].each do |genre|
      if Event.where.not(status: :completed).select { |event| event.inspo.genre == genre }.count.zero?
        event = Event.new
        event.date = Time.new(year, month, day, 19, [0, 30].sample) + (86400 * rand(1..5))
        event.inspo = Inspo.where(genre: genre).sample
        event.content = event.inspo.content if genre == 'text'
        event.partner = user.partner
        event.save!
      end
    end
    deficit = user.event_frequency - Event.where.not(status: :completed).where(partner_id: user.partner).count
    if deficit.positive?
      deficit.times do
        event = Event.new
        event.inspo = user.all_favorited.empty? ? Inspo.all.sample : user.all_favorited.sample
        event.partner = user.partner
        event.date = Time.new(Date.today.year, Date.today.month, Date.today.day, 19, [0, 30].sample) + (86400 * rand(1..5))
        event.save!
      end
    end
  end

  def send_message(attributes = {})
    require 'twilio-ruby'
    account_sid = ENV["TWILIO_ACCOUNT_SID"]
    auth_token = ENV["TWILIO_AUTH_TOKEN"]
    twilio_number = ENV["TWILIO_PHONE_NUMBER"]
    client = Twilio::REST::Client.new(account_sid, auth_token)
    content = attributes[:content]
    from = twilio_number
    to = '+14372270294' #hard-coded
    client.messages.create(from: from, to: to, body: content)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy edit_success update_success]
  skip_before_action :verify_authenticity_token
  before_action :completed_events

  def new
    @event = Event.new
  end

  def uncompleted_events
    @uncompleted_events = Event.where(partner_id: current_user.partner).where.not(status: :completed)
    @uncompleted_events = @uncompleted_events.sort_by(&:date)
  end

  def show
  end

  def create
    @event = Event.new(event_params)
    @event.partner = current_user.partner
    if @event.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @inspo = @event.inspo
  end

  def update
    @event.update(event_params)
    if @event.inspo.genre == 'date'
      EventMailer.with(event: @event, user: current_user).invite_email.deliver_now
      flash[:notice] = "A confirmation email has been sent to #{current_user.partner.name} ❤️❤️"
    elsif @event.inspo.genre == 'text'
      flash[:notice] = "#{@event.inspo.name.capitalize} will be sent to #{current_user.partner.name} ❤️❤️"
      @event.send_message(content: @event.content)
    end
    redirect_to dashboard_path
  end

  def destroy
    @event.destroy
    redirect_to dashboard_path
  end

  def edit_success
  end

  def update_success
    @event.success = !@event.success
    @event.save
    current_user.unfavorite(@event.inspo)
    respond_to do |format|
      format.html
      format.json { render json: @event }
    end
  end

  def completed_events
    if current_user.partner
      @completed_events = Event.where(partner_id: current_user.partner).select do |event|
        event.date && DateTime.now.in_time_zone('Eastern Time (US & Canada)') > event.date
      end
      if @completed_events.present?
        @completed_events.each(&:completed!)
        @completed_events = @completed_events.sort_by(&:date).reverse
      end
    end
  end

  def loading
    Event.load(current_user)
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:date, :success, :status, :content, :inspo_id)
  end

end

app/views/events/completed_events.html.erb
<div class="banner">
  <div>
    <h4>Past events</h4>
  </div>
</div>
<div class="banner-margin">
  <div class="wrapper">
    <div class="dashboard-info">
      <% if current_user.partner.nil? %>
        <div class="center-dashboard">
          <h2>You don't have <br> a partner yet.</h2>
          <%= link_to "Create a partner profile", new_partner_path, class: "btn-flat mt-3" %>
        </div>
      <% elsif current_user.partner.events.where(status: :completed).count.zero? %>
        <div class="center-dashboard">
          <h2 class="mb-3">You have no <br> past events.</h2>
          <%= link_to 'Create new event', new_event_path, class:"btn btn-flat mt-3" %>
          <%= link_to 'Generate new events', events_loading_path, class:"btn btn-flat mt-3"%>
        </div>
      <% end %>
    </div>
    <div class="events-list" data-controller="edit-event">
      <% if @completed_events.present? %>
        <% @completed_events.each do |event| %>
          <h6 class="mb-2"><%= event.date.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %b %e") %></h6>
          <div>
            <%= render "shared/event-card-completed", event: event %>
            <%= render "shared/show-event-card", event: event %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="wrapper">
  <%= render "shared/edit-event-card", event: @event %>
</div>

app/views/events/loading.html.erb
<%= image_tag("loading.gif", height: '600', width: '375') %>
<script type="text/javascript">
  setTimeout(() => { window.location.href="/dashboard"; }, 5000); // this should work like a charm!
</script>

app/views/events/new.html.erb
<div class="wrapper">
  <div class="form-wrapper">
    <h2 class="mb-2">New Event</h2>
    <div>
      <%= simple_form_for @event do |f| %>
        <%= f.association :inspo, label: "Choose a curated event:", input_html: { data: { controller: "tom-select" } } %>
        <%= f.input :date, html5: true, label: "Event due date:" %>
        <%= f.hidden_field :status, value: Event.statuses.key(1) %>
        <%= f.submit "Create Event", class: "btn btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="wrapper">
  <%= render "shared/show-event-card", event: @event %>
</div>

app/views/events/uncompleted_events.html.erb
<div class="banner">
  <div>
    <h4>
      <% hour = Time.now.in_time_zone('Eastern Time (US & Canada)').hour %>
      <% if hour > 3 && hour < 12 %>
        Good morning, <%= current_user.name %>
      <% elsif hour > 17 || hour <= 3 %>
        Good evening, <%= current_user.name %>
      <% else %>
        Good afternoon, <%= current_user.name %>
      <% end %>
    </h4>
    <h6 class="mt-2">Today is <%= Time.now.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %b %e") %></h6>
  </div>
</div>

<div class="banner-margin">
  <div class="wrapper">
    <div class="dashboard-info">
      <% if current_user.partner == nil %>
        <div class="center-dashboard">
          <h2>You don't have <br> a partner yet.</h2>
          <%= link_to "Create a partner profile", new_partner_path, class: "btn-flat mt-3" %>
        </div>
      <% elsif current_user.partner.events.where.not(status: :completed).count.zero? %>
        <div class="center-dashboard">
          <h2 class="mb-3">You have no <br> upcoming events.</h2>
          <%= link_to 'Create new event', new_event_path, class:"btn btn-flat mt-3" %>
          <%= link_to 'Generate new events', events_loading_path, class:"btn btn-flat mt-3"%>
        </div>
      <% else %>
        <h4 class="mb-2" style="text-align: left">Upcoming events</h4>
      <% end %>
    </div>
    <div class="events-list" data-controller="edit-event">
      <% @uncompleted_events.each do |event| %>
        <h6 class="mb-2"><%= event.date.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %b %e") %></h6>
        <div>
          <% if event.pending? %>
            <%= render "shared/event-card-pending", event: event %>
            <%= render "shared/edit-event-card", event: event %>
          <% elsif event.confirmed? %>
            <%= render "shared/event-card-confirmed", event: event %>
            <%= render "shared/show-event-card", event: event %>
          <% elsif event.completed? %>
            <%= render "shared/event-card-completed", event: event %>
            <%= render "shared/show-event-card", event: event %>
          <% end %>
        </div>
      <% end %>
      <div class="dashboard-info">
        <% if current_user.partner && current_user.partner.events.where.not(status: :completed).count.positive? %>
          <%= link_to 'Create new event', new_event_path, class:"btn btn-flat mt-3" %>
          <%= link_to 'Generate new events', events_loading_path, class:"btn btn-flat mt-3"%>
        <% end %>
      </div>
    </div>
  </div>
</div>