config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :partners, only: [:new, :create, :edit, :update, :destroy] do
    get '/keywords', to: 'keywords#index'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get 'events/loading', to: 'events#loading'
  resources :events, except: :index
  get '/dashboard', to: 'events#uncompleted_events', as: :dashboard
  get '/events/:id/success', to: 'events#edit_success', as: :success
  patch '/events/:id/success', to: 'events#update_success'
  get '/completed_events', to: 'events#completed_events', as: :history
  get '/us/', to: 'users#us', as: :us
  get '/settings/', to: 'users#setting', as: :setting
  get 'users/:id/edit', to: 'users#edit', as: :edit
  patch 'users/:id', to: "users#update", as: :update
  resources :inspos, only: %i[index edit update] do
    member do
      post 'toggle_favorite', to: "inspos#toggle_favorite"
      post 'toggle_blocked', to: "inspos#toggle_blocked"
    end
  end
  get '/preferences/create', to: 'preferences#create'
  get '/preferences/destroy', to: 'preferences#destroy'
  as :user do
    get '/us/', to: 'devise/registrations#edit', as: :user_root
  end
end

app/models/inspo.rb
class Inspo < ApplicationRecord
  has_many :events
  has_many :inspo_keywords
  has_many :keywords, through: :inspo_keywords

  validates :name, presence: true
  validates :genre, presence: true
  validates :genre, inclusion: { in: %w(date gift text), message: "%{value} must be one and only one of 'date', 'gift', and 'text'" }

  acts_as_favoritable

  has_one_attached :photo
end

app/controllers/inspos_controller.rb
class InsposController < ApplicationController
  def index
    if current_user && current_user.partner
      @inspos = current_user.partner.inspos.uniq.reject do |inspo|
        inspo.favorited_by?(current_user)
      end.reject do |inspo|
        current_user.blocked_by?(inspo)
      end.sample(5)
      @inspos = Inspo.all.sample(5) if @inspos.empty?
      # inspos = [Inspo.where(name: "Netflix and Chill")[0], Inspo.where(name: "Fishing Rod")[0], Inspo.where(name: "Send a Love Poem")[0]]
      # randos = Inspo.where.not(name: "Netflix and Chill").where.not(name: "Fishing Rod").where.not(name: "Send a Love Poem").sample(2)
      # @inspos = inspos | randos
    end
  end

  def toggle_favorite
    @inspo = Inspo.find_by(id: params[:id])
    current_user.favorite(@inspo)
  end

  def toggle_blocked
    @inspo = Inspo.find_by(id: params[:id])
    @inspo.block(current_user)
  end
end

app/views/inspos/index.html.erb
<div class="banner">
  <div>
    <h4>Choose your events</h4>
  </div>
</div>
<div class="banner-margin">
  <div class="wrapper">
    <div class="dashboard-info">
      <% if current_user.partner.nil? %>
        <div class="center-dashboard">
          <h2>You don't have <br> a partner yet.</h2>
          <%= link_to "Create a partner profile", new_partner_path, class: "btn-flat mt-3" %>
        </div>
      <% else %>
        <div data-controller="swipe-inspos">
          <% @inspos.each_with_index do |inspo, index| %>
            <%= render "shared/inspo-card", inspo: inspo, index: index, total: @inspos.count %>
          <% end %>
          <%= render "shared/loading" %>
          <% if current_user.all_favorites.count == 0 %>
            <div class="back-skip" style="margin-top: 9px">
              <%= link_to ('<i class="fa-solid fa-circle-arrow-left"></i> Back').html_safe, partner_keywords_path(@current_user.partner), class: "dark-link" %>
              <%= link_to ('Skip <i class="fa-solid fa-circle-arrow-right"></i>').html_safe, events_loading_path, class: "dark-link" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>