config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :partners, only: [:new, :create, :edit, :update, :destroy] do
    get '/keywords', to: 'keywords#index'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get 'events/loading', to: 'events#loading'
  resources :events, except: :index
  get '/dashboard', to: 'events#uncompleted_events', as: :dashboard
  get '/events/:id/success', to: 'events#edit_success', as: :success
  patch '/events/:id/success', to: 'events#update_success'
  get '/completed_events', to: 'events#completed_events', as: :history
  get '/us/', to: 'users#us', as: :us
  get '/settings/', to: 'users#setting', as: :setting
  get 'users/:id/edit', to: 'users#edit', as: :edit
  patch 'users/:id', to: "users#update", as: :update
  resources :inspos, only: %i[index edit update] do
    member do
      post 'toggle_favorite', to: "inspos#toggle_favorite"
      post 'toggle_blocked', to: "inspos#toggle_blocked"
    end
  end
  get '/preferences/create', to: 'preferences#create'
  get '/preferences/destroy', to: 'preferences#destroy'
  as :user do
    get '/us/', to: 'devise/registrations#edit', as: :user_root
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ficelle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/300f71314e.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= favicon_link_tag %>
    <meta property="fb:app_id" content="966242223397117"/>
  </head>

  <body>
    <div class="alert">
      <% flash.each do |type, msg| %>
        <% if type == "alert" %>
          <div class="alert flash flash-danger" role="alert" data-controller="alert">
            <%= msg %>
            <a data-alert-target="popup" data-action="click->alert#connect" data-bs-dismiss="alert" aria-label="Close">
            </a>
          </div>
        <% elsif type == "notice" %>
          <div class="alert alert-dismissible flash flash-success fade show" role="alert" data-controller="alert">
            <%= msg %>
            <a data-alert-target="popup" data-action="click->alert#connect" data-bs-dismiss="alert" aria-label="Close">
            </a>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
    <% unless request.fullpath == events_loading_path || request.fullpath == root_path || request.fullpath == new_partner_path || request.fullpath == partners_path %>
      <%= render "shared/navbar" %>
    <% end %>
  </body>
</html>